# Generated by Django 2.0.5 on 2019-06-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('empleado', '0002_auto_20190611_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.Recurso'),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Solicitud'),
        ),
        migrations.AddField(
            model_name='asignacionpuestoproyecto',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.Empleado'),
        ),
        migrations.AddField(
            model_name='asignacionpuestoproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
        migrations.AddField(
            model_name='asignacionpuestoproyecto',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Puesto'),
        ),
    ]
