# Generated by Django 2.0.5 on 2019-06-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20190611_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFinalizacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicioConstruccion',
            field=models.DateField(null=True),
        ),
    ]
