# Generated by Django 2.0.5 on 2019-06-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEjemplar', models.CharField(max_length=10)),
                ('nombreEjemplar', models.CharField(max_length=25)),
                ('descripcionEjemplar', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreHerramienta', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRecurso', models.CharField(max_length=10)),
                ('nombreRecurso', models.CharField(max_length=25)),
                ('tipoRecurso', models.CharField(max_length=20)),
                ('descripcionRecurso', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='idRecurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.Recurso'),
        ),
    ]
