# Generated by Django 2.0.5 on 2019-06-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionHerramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateField(auto_now_add=True)),
                ('fechaDisponible', models.DateField(auto_now_add=True)),
                ('Herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.Herramienta')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionoEjemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateField(auto_now_add=True)),
                ('fechaDisponible', models.DateField(auto_now_add=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.Ejemplar')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
    ]
