# Generated by Django 2.0.5 on 2019-06-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionherramienta',
            name='cantidadAsignada',
            field=models.IntegerField(default=0),
        ),
    ]
