# Generated by Django 2.0 on 2019-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numTelefono',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dui',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nit',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numTelefono',
            field=models.CharField(max_length=8),
        ),
    ]
