# Generated by Django 2.0.5 on 2019-06-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionherramienta',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asignacionoejemplar',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asignacionpuestoproyecto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
