# Generated by Django 2.0.5 on 2019-06-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='canatidadDisponibles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='cantidadHerramienta',
            field=models.IntegerField(default=0),
        ),
    ]
