# Generated by Django 2.0.5 on 2019-06-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0002_auto_20190623_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionherramienta',
            old_name='disponible',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='asignacionoejemplar',
            old_name='disponible',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='asignacionpuestoproyecto',
            old_name='disponible',
            new_name='activo',
        ),
    ]
