# Generated by Django 2.0.5 on 2019-06-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0002_auto_20190613_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='descripcionEjemplar',
            field=models.CharField(max_length=100),
        ),
    ]
