# Generated by Django 2.0.5 on 2019-06-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0002_asignacionherramienta_cantidadasignada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='puesto',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='Asignacion',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='constructora.AsignacionPuestoProyecto'),
        ),
    ]
