# Generated by Django 2.0.5 on 2019-06-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0002_solicitud_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructora.AsignacionPuestoProyecto'),
        ),
    ]
