# Generated by Django 2.0.5 on 2019-06-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0003_auto_20190623_1649'),
        ('constructora', '0003_auto_20190623_1847'),
    ]

    operations = [
    ]
