# Generated by Django 2.0.5 on 2019-06-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0003_auto_20190618_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolicitud',
            name='recurso',
            field=models.CharField(max_length=150),
        ),
    ]
