# Generated by Django 2.0.5 on 2019-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0004_auto_20190619_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
