# Generated by Django 2.0.5 on 2019-06-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0005_proyecto_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='disponibl',
            field=models.BooleanField(default=True),
        ),
    ]
