# Generated by Django 2.0.5 on 2019-06-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructora', '0006_empleado_disponibl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='disponibl',
            new_name='disponible',
        ),
    ]
