# Generated by Django 2.0.5 on 2019-06-12 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        ('empleado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Puesto'),
        ),
        migrations.AddField(
            model_name='asignacionusuario',
            name='empleado_proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto.AsignacionPuestoProyecto'),
        ),
        migrations.AddField(
            model_name='asignacionusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
