# Generated by Django 2.0.5 on 2019-06-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsistencia', models.DateField(auto_now_add=True)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Puesto')),
            ],
        ),
    ]
